- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: certs created
  command: letsencrypt certonly --standalone -d {{ ansible_fqdn }} -m {{ certbot_mail_address }}
  args:
    creates: "{{ certbot_live_home }}/{{ ansible_fqdn }}/fullchain.pem"
  when: certbot_create_certs

- name: renew certs every month
  cron:
    job: letsencrypt renew
    special_time: monthly
  when: certbot_renew_certs
